/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kmackay.swig.uECC;

public class uECC_HashContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected uECC_HashContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(uECC_HashContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        uECCSwigJNI.delete_uECC_HashContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInit_hash(SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext__void value) {
    uECCSwigJNI.uECC_HashContext_init_hash_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext__void getInit_hash() {
    long cPtr = uECCSwigJNI.uECC_HashContext_init_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext__void(cPtr, false);
  }

  public void setUpdate_hash(SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_q_const__unsigned_char_unsigned_int__void value) {
    uECCSwigJNI.uECC_HashContext_update_hash_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_q_const__unsigned_char_unsigned_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_q_const__unsigned_char_unsigned_int__void getUpdate_hash() {
    long cPtr = uECCSwigJNI.uECC_HashContext_update_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_q_const__unsigned_char_unsigned_int__void(cPtr, false);
  }

  public void setFinish_hash(SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_unsigned_char__void value) {
    uECCSwigJNI.uECC_HashContext_finish_hash_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_unsigned_char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_unsigned_char__void getFinish_hash() {
    long cPtr = uECCSwigJNI.uECC_HashContext_finish_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__struct_uECC_HashContext_p_unsigned_char__void(cPtr, false);
  }

  public void setBlock_size(long value) {
    uECCSwigJNI.uECC_HashContext_block_size_set(swigCPtr, this, value);
  }

  public long getBlock_size() {
    return uECCSwigJNI.uECC_HashContext_block_size_get(swigCPtr, this);
  }

  public void setResult_size(long value) {
    uECCSwigJNI.uECC_HashContext_result_size_set(swigCPtr, this, value);
  }

  public long getResult_size() {
    return uECCSwigJNI.uECC_HashContext_result_size_get(swigCPtr, this);
  }

  public void setTmp(SWIGTYPE_p_unsigned_char value) {
    uECCSwigJNI.uECC_HashContext_tmp_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getTmp() {
    long cPtr = uECCSwigJNI.uECC_HashContext_tmp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public uECC_HashContext() {
    this(uECCSwigJNI.new_uECC_HashContext(), true);
  }

}
