/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kmackay.swig.uECC;

public interface uECCSwigConstants {
  public final static int uECC_arch_other = uECCSwigJNI.uECC_arch_other_get();
  public final static int uECC_x86 = uECCSwigJNI.uECC_x86_get();
  public final static int uECC_x86_64 = uECCSwigJNI.uECC_x86_64_get();
  public final static int uECC_arm = uECCSwigJNI.uECC_arm_get();
  public final static int uECC_arm_thumb = uECCSwigJNI.uECC_arm_thumb_get();
  public final static int uECC_arm_thumb2 = uECCSwigJNI.uECC_arm_thumb2_get();
  public final static int uECC_arm64 = uECCSwigJNI.uECC_arm64_get();
  public final static int uECC_avr = uECCSwigJNI.uECC_avr_get();
  public final static int uECC_OPTIMIZATION_LEVEL = uECCSwigJNI.uECC_OPTIMIZATION_LEVEL_get();
  public final static int uECC_SQUARE_FUNC = uECCSwigJNI.uECC_SQUARE_FUNC_get();
  public final static int uECC_VLI_NATIVE_LITTLE_ENDIAN = uECCSwigJNI.uECC_VLI_NATIVE_LITTLE_ENDIAN_get();
  public final static int uECC_SUPPORTS_secp160r1 = uECCSwigJNI.uECC_SUPPORTS_secp160r1_get();
  public final static int uECC_SUPPORTS_secp192r1 = uECCSwigJNI.uECC_SUPPORTS_secp192r1_get();
  public final static int uECC_SUPPORTS_secp224r1 = uECCSwigJNI.uECC_SUPPORTS_secp224r1_get();
  public final static int uECC_SUPPORTS_secp256r1 = uECCSwigJNI.uECC_SUPPORTS_secp256r1_get();
  public final static int uECC_SUPPORTS_secp256k1 = uECCSwigJNI.uECC_SUPPORTS_secp256k1_get();
  public final static int uECC_SUPPORT_COMPRESSED_POINT = uECCSwigJNI.uECC_SUPPORT_COMPRESSED_POINT_get();
  public final static int uECC_PLATFORM = uECCSwigJNI.uECC_PLATFORM_get();
  public final static int uECC_ARM_USE_UMAAL = uECCSwigJNI.uECC_ARM_USE_UMAAL_get();
  public final static int uECC_WORD_SIZE = uECCSwigJNI.uECC_WORD_SIZE_get();
  public final static int SUPPORTS_INT128 = uECCSwigJNI.SUPPORTS_INT128_get();
  public final static int HIGH_BIT_SET = uECCSwigJNI.HIGH_BIT_SET_get();
  public final static int uECC_WORD_BITS = uECCSwigJNI.uECC_WORD_BITS_get();
  public final static int uECC_WORD_BITS_SHIFT = uECCSwigJNI.uECC_WORD_BITS_SHIFT_get();
  public final static int uECC_WORD_BITS_MASK = uECCSwigJNI.uECC_WORD_BITS_MASK_get();
}
