/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package kmackay.swig.uECC;

public class uECCSwig implements uECCSwigConstants {
  public static SWIGTYPE_p_unsigned_char new_uint8Array(int nelements) {
    long cPtr = uECCSwigJNI.new_uint8Array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static void delete_uint8Array(SWIGTYPE_p_unsigned_char ary) {
    uECCSwigJNI.delete_uint8Array(SWIGTYPE_p_unsigned_char.getCPtr(ary));
  }

  public static short uint8Array_getitem(SWIGTYPE_p_unsigned_char ary, int index) {
    return uECCSwigJNI.uint8Array_getitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index);
  }

  public static void uint8Array_setitem(SWIGTYPE_p_unsigned_char ary, int index, short value) {
    uECCSwigJNI.uint8Array_setitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_uECC_Curve_t uECC_secp160r1() {
    long cPtr = uECCSwigJNI.uECC_secp160r1();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uECC_Curve_t(cPtr, false);
  }

  public static SWIGTYPE_p_uECC_Curve_t uECC_secp192r1() {
    long cPtr = uECCSwigJNI.uECC_secp192r1();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uECC_Curve_t(cPtr, false);
  }

  public static SWIGTYPE_p_uECC_Curve_t uECC_secp224r1() {
    long cPtr = uECCSwigJNI.uECC_secp224r1();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uECC_Curve_t(cPtr, false);
  }

  public static SWIGTYPE_p_uECC_Curve_t uECC_secp256r1() {
    long cPtr = uECCSwigJNI.uECC_secp256r1();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uECC_Curve_t(cPtr, false);
  }

  public static SWIGTYPE_p_uECC_Curve_t uECC_secp256k1() {
    long cPtr = uECCSwigJNI.uECC_secp256k1();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uECC_Curve_t(cPtr, false);
  }

  public static void uECC_set_rng(SWIGTYPE_p_f_p_unsigned_char_unsigned_int__int rng_function) {
    uECCSwigJNI.uECC_set_rng(SWIGTYPE_p_f_p_unsigned_char_unsigned_int__int.getCPtr(rng_function));
  }

  public static SWIGTYPE_p_f_p_unsigned_char_unsigned_int__int uECC_get_rng() {
    long cPtr = uECCSwigJNI.uECC_get_rng();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_unsigned_char_unsigned_int__int(cPtr, false);
  }

  public static int uECC_curve_private_key_size(SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_curve_private_key_size(SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_curve_public_key_size(SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_curve_public_key_size(SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_make_key(SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_unsigned_char private_key, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_make_key(SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_unsigned_char.getCPtr(private_key), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_shared_secret(SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_unsigned_char private_key, SWIGTYPE_p_unsigned_char secret, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_shared_secret(SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_unsigned_char.getCPtr(private_key), SWIGTYPE_p_unsigned_char.getCPtr(secret), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static void uECC_compress(SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_unsigned_char compressed, SWIGTYPE_p_uECC_Curve_t curve) {
    uECCSwigJNI.uECC_compress(SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_unsigned_char.getCPtr(compressed), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static void uECC_decompress(SWIGTYPE_p_unsigned_char compressed, SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_uECC_Curve_t curve) {
    uECCSwigJNI.uECC_decompress(SWIGTYPE_p_unsigned_char.getCPtr(compressed), SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_valid_public_key(SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_valid_public_key(SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_compute_public_key(SWIGTYPE_p_unsigned_char private_key, SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_compute_public_key(SWIGTYPE_p_unsigned_char.getCPtr(private_key), SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_sign(SWIGTYPE_p_unsigned_char private_key, SWIGTYPE_p_unsigned_char message_hash, long hash_size, SWIGTYPE_p_unsigned_char signature, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_sign(SWIGTYPE_p_unsigned_char.getCPtr(private_key), SWIGTYPE_p_unsigned_char.getCPtr(message_hash), hash_size, SWIGTYPE_p_unsigned_char.getCPtr(signature), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_sign_deterministic(SWIGTYPE_p_unsigned_char private_key, SWIGTYPE_p_unsigned_char message_hash, long hash_size, uECC_HashContext hash_context, SWIGTYPE_p_unsigned_char signature, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_sign_deterministic(SWIGTYPE_p_unsigned_char.getCPtr(private_key), SWIGTYPE_p_unsigned_char.getCPtr(message_hash), hash_size, uECC_HashContext.getCPtr(hash_context), hash_context, SWIGTYPE_p_unsigned_char.getCPtr(signature), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

  public static int uECC_verify(SWIGTYPE_p_unsigned_char public_key, SWIGTYPE_p_unsigned_char message_hash, long hash_size, SWIGTYPE_p_unsigned_char signature, SWIGTYPE_p_uECC_Curve_t curve) {
    return uECCSwigJNI.uECC_verify(SWIGTYPE_p_unsigned_char.getCPtr(public_key), SWIGTYPE_p_unsigned_char.getCPtr(message_hash), hash_size, SWIGTYPE_p_unsigned_char.getCPtr(signature), SWIGTYPE_p_uECC_Curve_t.getCPtr(curve));
  }

}
